// <auto-generated />
namespace Rest.Web.Engineer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2012018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2012018));
        
        string IMigrationMetadata.Id
        {
            get { return "201801021703001_2-01-2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
